### PR TITLE
DOC: Make some formatting changes and add a "Using dat" section

### PR DESCRIPTION
**Pull request by waldoj**
These two commits are isolated, with one making general improvements to the text, the other adding a new section entirely.

### CODE REVIEW

**Comment by karissa** [comment]
This is great! The exoplanets example could be changed to import directly from a url - dat handles that

**Comment by karissa** [comment]
@waldoj I guess what confuses me here is that you say to put the csv into the same directory, but really the dat should replace the csv, so you should import it to the dat from wherever it happens to be on your filesystem or on the web

**Comment by waldoj** [comment]
I was writing this while also struggling (and failing) to install dat on my local machine, so I couldn't test it to see if that more efficient route would work. :) I've got that improved now. I sure don't think that this is a brilliant "Using dat" section, but I figure it's better than nothing, and at least starts to address the concern raised by @mlissner in #364, that there needs to be a quick way for somebody to be able to play with dat.

I'd really like to see this section instead fork an existing dataset, so somebody can try changing it, seeing a diff, etc. Baby steps. :)

**Comment by karissa** [comment]
lgtm!

**Pull request merged**
