### PR TITLE
Add ignore pattern in a dat configuration file

### PR DESCRIPTION
**Pull request by karissa**
This PR adds the ability to specify a list of ignore patterns in a `dat.json` file.

For example, I want to share the following directory structure using dat:

```
$ dat link .
Creating Dat Link (4 files, 3 folders, 1.5 kB total)
[Done] ignore.me
[Done] folder/empty.txt
[Done] all_hour.csv
[Done] Files Read to Dat: 4 of 4 (1.5 kB of 1.5 kB)
[Sharing] dat://d2d978350ac5621f141a7633e9c1055bd15bd2f5100cc69fc4901f9cda33d9e2
[Status] Connected to 0 sources
```

I can create a pattern to ignore the `ignore.me` file by creating `dat.json` in the cwd:

dat.json
```
{
  "ignore": [ "*.me" ]
}
```

When I run `dat link` again, it will not include `ignore.me` in the new :

```
$ dat link .
Creating Dat Link (4 files, 3 folders, 1.5 kB total)
[Done] folder/empty.txt
[Done] dat.json
[Done] all_hour.csv
[Done] Files Read to Dat: 4 of 4 (1.5 kB of 1.5 kB)
[Sharing] dat://01fcfb25c487b7c9eb2e514482a34cc0ffd635c9f790e337c8764066e5f5fbc8
[Status] Connected to 0 sources
```

### CODE REVIEW

**Comment by karissa** [comment]
There's a bug caused by a UX oddity:

When you link a single folder, the user might think a dat.json file inside that folder is the one being used, but it is actually looking for one in the `cwd`
```
tests $ dat link fixtures/
Creating Dat Link (4 files, 3 folders, 1.5 kB total)
[Done] fixtures/ignore.me
[Done] fixtures/folder/empty.txt
[Done] fixtures/dat.json
[Done] fixtures/all_hour.csv
[Done] Files Read to Dat: 4 of 4 (1.5 kB of 1.5 kB)
[Sharing] dat://d2d978350ac5621f141a7633e9c1055bd15bd2f5100cc69fc4901f9cda33d9e2
[Status] Connected to 0 sources
^
```

**Comment by lukeburns** [comment]
Started on a similar project before seeing this (woops!). Implemented it on the folder-walker level. Here's my PR there: https://github.com/karissa/folder-walker/pull/4.

Implementing in dat would amount to replacing

```js
var stream = walker(dirs, {filter: function (data) {
    if (path.basename(data) === '.dat') return false
    return true
  }})
```

with

```js
var stream = walker(dirs, { ignore: '.dat', ignoreFiles: '.datignore' })
```

This approach allows you to have .datignore files for different directories.

**Comment by karissa** [comment]
@lukeburns we are holding off for a minute on this, because we have to do some refactoring in the dat cli/core, but I like where you're headed!

I am leaning towards having just one `dat.json` or `dat.yml` file for a single directory which has all of the configuration options for your dat (including ignores, remote syncs, maybe also collaborators). We have recently been talking about how git hides a lot of its configuration options behind hidden files and folders, which makes it more difficult for new folks to come in and learn how to configure! What do you think about this idea?

**Comment by lukeburns** [comment]
Yeah, I think that makes a lot of sense for scientists. Are there plans to expose a lower level interface for developers to build on dat?

**Comment by lukeburns** [comment]
Though, I might add that having a single configuration file ties dat to a particular root project directory. I like that it's currently _not_ tied to some root project directory.

Also, note: the latest PR https://github.com/karissa/folder-walker/pull/4 can be used to process different kinds of configuration files (e.g. json or yml) as well as handle ignore rules specific to subdirectories.

**Pull request closed without merging**
