### PR TITLE
correct ESGF link

### PR DESCRIPTION
**Pull request by ajschumacher**
esgf.org is non-functioning; see also https://github.com/ESGF/esgf.github.io/issues/6

### CODE REVIEW

**Comment by ajschumacher** [comment]
ping @maxogden

**Comment by mafintosh** [comment]
:+1:

**Comment by mafintosh** [comment]
good catch. thanks for the patch

**Comment by mafintosh** [comment]
hey that rhymed!

**Comment by ajschumacher** [comment]
+1 rhymes / all the times

**Comment by karissa** [comment]
:+1: :musical_note:

**Pull request merged**
