### PR TITLE
adds --list option to download

### PR DESCRIPTION
**Pull request by joehand**
List file names, file count, and size for a dat link with `--list` option on `dat <link>`

## In Progress List
screen shot 2016-06-09 at 15 45 04

## Completed List
screen shot 2016-06-09 at 15 45 12

### CODE REVIEW

**Comment by mafintosh** [comment]
currently this will still download file data in the background. working on a fix for that.

**Comment by mafintosh** [comment]
looking great otherwise! 👍

**Comment by juliangruber** [comment]
👍 that's great!

**Comment by joehand** [comment]
This is included in #485

**Pull request closed without merging**
