### PR TITLE
update Travis-CI configuration

### PR DESCRIPTION
**Pull request by optikfluffel**
I just removed the unnecessary default steps that Travis does anyway and made it use it's [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/).

### CODE REVIEW

**Comment by karissa** [comment]
looks good to me!

**Comment by optikfluffel** [comment]
Rebased on current master branch.

**Comment by shinnn** [comment]
LGTM

**Comment by maxogden** [comment]
whoa nice, didn't even know containers were a thing on travis. thanks!

**Pull request merged**
