### PR TITLE
Fix #355

### LINKED ISSUE #355: Better handling of SIGPIPE exceptions
Dat should gracefully handle `SIGPIPE` exceptions:

```
› dat keys -d genes | head
A1BG
A1BG-AS1
A1CF
A2M
A2M-AS1
A2ML1
A2ML1-AS1
A2ML1-AS2
A2MP1
A3GALT2
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
```

### PR DESCRIPTION
**Pull request by bmpvieira**

### CODE REVIEW

**Comment by maxogden** [comment]
@bmpvieira thanks!! @mafintosh would you recommend this over `require('epipebomb')` in this scenario?

**Comment by mafintosh** [comment]
@maxogden @bmpvieira good quesion. [epipebomb](https://github.com/mhart/epipebomb) will make the process exit nicer since it doesn't kill the event loop so i probably like that a little more since that'll mean that any pending writes will be flushed (if there are any)

**Comment by bmpvieira** [comment]
Cool, I didn't know about ```epipebomb```. I'll start using that in bionode. However, it has some issues with ```single-line-log```.

```bash
dat -d genes keys | head -n 1
cic98n49c00009cs0qxdwr7b3
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: This socket is closed.
    at Socket._writeGeneric (net.js:656:19)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Socket.stream.write (/Users/bmpvieira/GitHub/dat/node_modules/single-line-log/index.js:11:16)
    at process.<anonymous> (/Users/bmpvieira/GitHub/dat/node_modules/single-line-log/index.js:15:28)
    at process.emit (events.js:129:20)
    at process.exit (node.js:600:17)
```

**Comment by maxogden** [comment]
@mafintosh o/ was that the single-line-log bug you found when we were pairing recently?

**Comment by mafintosh** [comment]
@maxogden hmm this is happening because single-line-log is wrapping process.stdout to detect some stuff. i'll try to see if there is a nice way to fix that

@bmpvieira we should probably just revert to using the process.exit in that incase since that works fine as well

**Comment by karissa** [comment]
what's the status on this one?

**Comment by karissa** [comment]
I put this into abort.js instead, so it only happens on error

**Pull request closed without merging**
